train: C:/Users/Arnis KC/Desktop/Create-with-code/TrafficAI/data/images
val: C:/Users/Arnis KC/Desktop/Create-with-code/TrafficAI/data/images  
test: C:/Users/Arnis KC/Desktop/Create-with-code/TrafficAI/data/images

nc: 2
names:
  0: Without Helmet
  1: With Helmet
